title: Nicholas Babafemi
logo: luke-chesser-JKUTrJ4vK00-unsplash.jpg
description: Welcome to my GitHub! I’m a data analyst with over two years of experience turning raw data into actionable insights that drive informed decision-making.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal

