title: Nicholas Babafemi
logo: https://github.com/NicholasBabs/Nicholasbabs.github.io/blob/main/luke-chesser-JKUTrJ4vK00-unsplash.jpg
description: 
Welcome to my GitHub! I’m a data analyst with over two years of experience turning raw data into actionable insights that drive informed decision-making. My expertise lies in working with diverse data sources, performing statistical analysis, and uncovering trends to support business strategies.
I specialize in-
Data Analysis & Visualization -Proficient in Excel, SQL, and Power BI to create impactful dashboards and reports.
Problem Solving & Insight Generation - Extracting meaningful insights to solve complex problems and inform decisions.
With a strong foundation in data mining, visualization, and manipulation, I thrive on delivering polished, detail-oriented analytical solutions. My goal is to use data-driven approaches to contribute to the success of dynamic organizations.
Here, you’ll find projects showcasing my ability to work with real-world datasets and build interactive dashboards. Let’s connect and explore how data can unlock opportunities!
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
